### ISSUE TITLE
Needs added support for historical dividends.

### ISSUE THREAD

**Issue by damianialex** [ranaroussi/fix-yahoo-finance#10]
Before, the yahoo finance package allowed us to pull historical dividend data with the command

    import pandas_datareader.data as web
    f = web.DataReader("F", 'yahoo-dividends', start="2017-01-01", end="2017-04-30")

However, there appears to be no way to do this with the yahoo fix package.
I have tried multiple commands with no success:

    import fix_yahoo_finance as yf
    import pandas_datareader.data as web

    # first attempt
    yf.download("IBM", actions="only", start="2017-01-01", end="2017-04-30")

    # second attempt
    yf.pandas_datareader.DataReader("F", 'yahoo-dividends', start="2017-01-01", end="2017-04-30")

**Comment by ranaroussi** [comment]
Just use the module as you normally use, but add either ``actions=True`` to get actions alongside the OHLCV data, or``actions='only'`` to get a only actions.

```python
from pandas_datareader import data as pdr
import fix_yahoo_finance as yf

#  get ohlcv data only
ohlcv = pdr.get_data_yahoo("AAPL", start="2015-01-01")

#  get actions alongside ohlcv data
ohlcva = pdr.get_data_yahoo("AAPL", actions=True, start="2015-01-01")

# get actions only dataframe
actions = pdr.get_data_yahoo("AAPL", actions='only', start="2015-01-01")
```

Hope that helps

**Comment by damianialex** [comment]
I used the `actions=True` tag which will modify all of the stock price data. However, I want to get the cash dividend payment at all the ex-dividend dates. I am unable to do this currently.

**Comment by ranaroussi** [comment]
Use `actions='only'`

Example:

```python
actions = pdr.get_data_yahoo("AAPL", actions='only', start="2015-01-01")
```

**Comment by damianialex** [comment]
Using 

`pdr.get_data_yahoo("AAPL", actions='only', start="2015-01-01")`

gives daily historical data of  

'[Open, High, Low, Close, Adj Close, Volume]`

What I'm hoping for is something like this 

        Date	        Dividends
	May 16, 2017	0.39 Dividend
	Feb 14, 2017	0.39 Dividend
	Nov 15, 2016	0.39 Dividend
	Aug 16, 2016	0.36 Dividend
