### ISSUE TITLE
Interval = "m" 

### ISSUE THREAD

**Issue by mynumbercrunching** [ranaroussi/fix-yahoo-finance#15]
the yahoo historical interval options seems to have been wiped out with this fix?
thanks for the yahoo fix.

>>> from pandas_datareader import data as pdr
>>> import fix_yahoo_finance
>>> data = pdr.get_data_yahoo("SPY", start="2015-01-01", end="2017-04-30", interval='m')
>>> data
Empty DataFrame
Columns: []
Index: []

**Comment by ranaroussi** [comment]
Please use `n`Interval = `1m`
