### ISSUE TITLE
reason: cannot reindex from a duplicate axis

### ISSUE THREAD

**Issue by rc3097** [ranaroussi/fix-yahoo-finance#17]
same issue here: https://github.com/ranaroussi/fix-yahoo-finance/issues/14
But the reason is that the datasource(yahoo) has the issue, like MBVT, has two values in a day (2017-05-12). `u'Date,Open,High,Low,Close,Adj Close,Volume\n2017-05-12,49.650002,49.849998,49.250000,49.799999,49.799999,49300\n2017-05-12,0.000000,49.849998,49.400002,49.799999,49.799999,24398\n'
` PTAL

**Comment by rc3097** [comment]
The best way to fix is that add     _DFS_={}  and fail when there are multi index

**Comment by ranaroussi** [comment]
Should be fixed in v 0.0.17 :)

Upgrade using:

```bash
$ pip install fix_yahoo_finance --upgrade --no-cache-dir
```

**Comment by Hasgassa** [comment]
I'm facing this issue on version 0.0.18.

Thank you
