### ISSUE TITLE
Return date before start date

### ISSUE THREAD

**Issue by Hasgassa** [ranaroussi/fix-yahoo-finance#18]
data = pdr.get_data_yahoo('A', actions='only', start='2017-04-01', end='2017-05-31') #actions only

Result:
[*********************100%***********************]  1 of 1 downloaded
Date    value    action            
2017-03-31  0.132  DIVIDEND

Why did I get 31 March 2017 if start Date is in April 2017?

Thank you once more! (is never enought :))

**Comment by ranaroussi** [comment]
That's a question for Yahoo I guess. lol

**Comment by Hasgassa** [comment]
Should I filter on my side?
Thanks

**Comment by Hasgassa** [comment]
I've created a function to validate the dataframe, just in case anyone needs it, follows below:
def validatedataframe(start,df,logfile):
    try:
        for index, row in df.iterrows():
            if left(str(index),10) < left(str(start),10):
                logfile.write("Index removed " + left(str(index),10) + " for being earlier to " + left(str(start),10),1)
                f.drop(index, inplace=True)
    except Exception as err:
        print("Error: " + inspect.stack()[0][3] + ": Validate Function Failed - " + str(err),0)
        return df;
    return df;
