### ISSUE TITLE
Writing to a File, 

### ISSUE THREAD

**Issue by johnx466** [ranaroussi/fix-yahoo-finance#24]
Thanks for taking time to write Ranaroussi,  Appreciate it,  Great Job, 

import fix_yahoo_finance as yf
data = yf.download("SPY", start="2017-01-01", end="2017-04-30")

I have trouble in writing to a file, how to write the ouput from Data or from yf.download directly into the file.

Also
print data  <<<< also shows only 20 lines, not all the 100 lines, 

Thanks and much appreciate it 

Johnx

**Comment by pushnyakov** [comment]
@johnx466 It returns pandas dataframe. To write it to csv you should use 
```python
data.to_csv('your/path.csv')

**Comment by johnx466** [comment]
Thanks Pushnyakov,  Great Job,  thanks
