### ISSUE TITLE
Is there a way to download the yahoo data from the earliest available date?

### ISSUE THREAD

**Issue by samuelyusunwang** [ranaroussi/fix-yahoo-finance#25]
Hi there:

See example below. Is there a way to download SPY data from its earliest available date without specifying the start date? The function use default value '1950-1-1', but it creates an error.

Thanks,
D

# Code
import pandas_datareader.data as web
import fix_yahoo_finance as yf
yf.pdr_override()
data = web.get_data_yahoo('SPY')

#Error

  File "<ipython-input-32-af29ab3df16e>", line 1, in <module>
    data = web.get_data_yahoo('SPY')

  File "C:\Continuum\Anaconda3\lib\site-packages\fix_yahoo_finance\__init__.py", line 147, in download
    start = int(time.mktime(time.strptime('1950-01-01', '%Y-%m-%d')))

OverflowError: mktime argument out of range

**Comment by Hasgassa** [comment]
Anything before 1970-01-01 ( start of time :) ) is returning this error.

Maybe yahoo fix may be fixed? :)
[](https://stackoverflow.com/questions/2518706/python-mktime-overflow-error)

Thank you.

**Comment by underdpt** [comment]
For me, it's working if I fetch the data from 1971-01-01 (+1 year)
