### ISSUE TITLE
Usage with Anaconda/iPython?

### ISSUE THREAD

**Issue by yyiri** [ranaroussi/fix-yahoo-finance#27]
Hi - thanks for the package, works great.

Question - is it possible to use this on iPython/Anaconda?

Thanks!

**Comment by renium** [comment]
I use it with Anaconda and with Python2 and Python3.
The problem I am faced is, that approximately every third request 
returns an empty dataframe......
I really doubt, that this is a Yahoo error...

**Comment by AnthonyFJGarner** [comment]
A whole string of empty dataframes returned after the first few successful ones

**Comment by rosdyana** [comment]
Hi, I have problem when try download another ticker, it will merge into one dataframe, how to separate dataframe per each session? 

my piece of codes
```

etf_a = ['spy','tlt']
etf_b = ['vwo','vti']

start = datetime(2001,1,1)
end    = datetime(2017,1,1)

data_a = pdr.get_data_yahoo(etf_a, start, end)['Adj Close']
data_b = pdr.get_data_yahoo(etf_b, start, end)['Adj Close']

print(len(data_a.columns)) # it will be 2 etf
print(len(data_b.columns))# should be 2, but it return 4, likely merge with previous downloaded data
```

any idea will be most appreciated, thanks!
