### ISSUE TITLE
fix-yahoo-finance: pip install not working

### ISSUE THREAD

**Issue by svijay1973** [ranaroussi/fix-yahoo-finance#28]
Hi Rana,

I am getting an error trying to install this...I am using python 3.6
```
MacBooks-MacBook-Air:~ svijay$ $ pip install fix_yahoo_finance --upgrade --no-cache-dir
-bash: $: command not found
```
Please advise!

**Comment by pmularien** [comment]
Looks like you have an extra `$` in there...

**Comment by manan904** [comment]
@pmularien is correct...

Copy paste this line on the terminal and run it-

`pip install fix_yahoo_finance --upgrade --no-cache-dir`
