### ISSUE TITLE
version for 2.7

### ISSUE THREAD

**Issue by bkcollection** [ranaroussi/fix-yahoo-finance#3]
Do you have a version for 2.7? 
I tested it and not working as it support 3.4 above

**Comment by ranaroussi** [comment]
No plans for it atm. Sorry

**Comment by ranaroussi** [comment]
Version 0.0.14 now supports Python 2.7!

Upgrade using:

```bash
$ pip install fix_yahoo_finance --upgrade --no-cache-dir
```
