### ISSUE TITLE
Looping through downloaded data?

### ISSUE THREAD

**Issue by arrabal** [ranaroussi/fix-yahoo-finance#33]
I know this is a noobish question, but I have no idea how to loop or iterate over the downloaded data. I've try to loop as in a python list or like in a numpy array, but I don't achieve it.

Can you provide a basic example? 

The line I use to download: 

`data = yf.download("BBVA.MC", start="2017-01-01", end="2017-04-30")`

Thank you

**Comment by yuj123** [comment]
Usually, pandas series is manipulated by numpy. If you would like to iterate it, you may use apply

def main():
	data = yf.download("BBVA.MC", start="2017-01-01", end="2017-04-30")
	
	data[["Close", "Volume"]].apply(lambda col: print("%.2f x %d = %.2f" % (col[0], col[1], col[0] * col[1])),axis=1)
	
main()

Result:
6.44 x 19607737 = 126273826.28
6.57 x 160332414 = 1052582297.91
6.50 x 179333129 = 1164768672.86
6.52 x 144550880 = 942182635.84
6.57 x 113930823 = 748069783.82
6.54 x 33421900 = 218478960.30

**Comment by arrabal** [comment]
Thank you.
