### ISSUE TITLE
stock BF.B and BRK.B can NOT be get from yahoo

### ISSUE THREAD

**Issue by tangvip** [ranaroussi/fix-yahoo-finance#38]
simply does not work. empty data

**Comment by jainraje** [comment]
try using a '-' as opposed to the '.' before ether B character (i.e. BF-B and BRK-B). Some providers use a '.' others use a '-' and yet others may use '/' or nothing at all.

**Comment by tangvip** [comment]
Thanks a lot. I found out the issue.

**Comment by jainraje** [comment]
@tangvip fyi you should close this issue.
