### ISSUE TITLE
Why 5 seconds wait for new cookie it takes hours to download 1700 tickers

### ISSUE THREAD

**Issue by fclr** [ranaroussi/fix-yahoo-finance#4]
Ran, thank you for creating this. I was about to do the same, but you saved me a lot of time. One question, why wait 5 seconds for the new cookie request? It takes hours to download the 1700 tickers I used to download in 30 minutes... every 2 or 3 tickers, the code lags for 5  seconds... Thank you again

**Comment by ranaroussi** [comment]
I removed the 5s wait in version 0.0.8 and instead lowered the cookie ttl to 3 min. I also keep track of all failed downloads and retries them later.

Upgrade using:

```bash
$ pip install fix_yahoo_finance --upgrade --no-cache-dir
```

and let me know if you see better results.

**Comment by fclr** [comment]
Ran,
I've cleaned up my ticker list to remove all tickers that weren't good anymore and used your 0.8 version and it took about 10-12 min to dowload +/- 1200 tickers with a dsl connection. This is incredible! Thank you so much! Keep up the great work.
