### ISSUE TITLE
Zero-size array

### ISSUE THREAD

**Issue by Filiprb** [ranaroussi/fix-yahoo-finance#43]
Hello,

I am using the following code to download data to Python:

`
import fix_yahoo_finance as yf
from pandas_datareader import data as pdr
yf.pdr_override()

ticker=['^GDAXI']

#ticker=['^GDAXI','EURUSD=X']

data = pdr.get_data_yahoo(ticker, start="2010-12-02", end="2018-01-31", as_panel = False)

data=data[['Open','High', 'Low', 'Adj Close', 'Volume']]
`

And it works perfekt 60% of the time. But often i get the following the error message:

"zero-size array to reduction operation maximum which has no identity"

When this occures, I usually have to restart my console in order to download data again. Is there any solution to this? Much appricirated!

**Comment by hrpomrx** [comment]
Also see this about the same frequency as you. I'm working in a Jupyter notebook; restarting the kernel does not solve this issue, at least not all of the time.

**Comment by akhodeir** [comment]
I also have the same issue !!

**Comment by hrpomrx** [comment]
It is definitely rate-limiting as Jordan says.

**Comment by akhodeir** [comment]
I don't think this is the correct explanation.
If I change the ticker, the program starts to work again for few trials.
it seems it is sporadic thing

**Comment by cvazquezlos** [comment]
Which solution do you propose to this?

**Comment by junikim95** [comment]
Hello
Did you find the solution?
If you make the number of 'thread' as smaller, it will be better.
Please check and let me know it works properly.

**Comment by zwep** [comment]
@akhodeir exactly, it is quite sporadic... first try: gave me the error.. then I read your comment, tried again: presto. Got the data I needed.

One hacky-solution is of course to write some kind of while loop with a try function..

**Comment by j6k4m8** [comment]
@zwep I have a feeling that won't do what you want: Even though it _seems_ like it's a sporadic failure, if it is indeed a rate-limit, then a loop will guarantee that you never shrink below the limit, and _always_ run into the rate limiter. Although of course, empirical proof to the contrary would be interesting :)

**Comment by j6k4m8** [comment]
By the way, you may also get this error if you attempt to download data for a day on which markets were closed (since Yahoo will return an empty response). Though that doesn't explain sporadic results, it may help you denoise your debugging process :)

**Comment by kennedyCzar** [comment]
I happen to have met similar challenge but solved it using a try catch method.
The reason for this error is simple because the stock/ticker is not available for free using the yahoo_api.
My guess is that they placed a restriction on download of the ticker name, hence the error.

This worked for me:
try:
    df = yahoo.download(self.TICK_SYMBOLS, start = self.START, end = datetime.now())
    df.reset_index(inplace = True)
    df.set_index("Date", inplace = True)
except ValueError:
    pass

Hope this helps for you.
Regards
