### ISSUE TITLE
Threads not working

### ISSUE THREAD

**Issue by Sdoof** [ranaroussi/fix-yahoo-finance#45]
Hello

I am running your code with 100 symbols (see enclosed), sadly I am getting the following errors when setting threads =10. The code works however with Threads =1
I would be really grateful if you could show me how to fix this as I am new to Python
[yahoo_finance.py.txt](https://github.com/ranaroussi/fix-yahoo-finance/files/1725185/yahoo_finance.py.txt)
 
`Traceback:
  File "/home/olivier/BNC/DATA_SCRAPER/yahoo_finance.py", line 138, in <module>
    threads=10
  File "/home/olivier/PycharmProjects/Pairs Trading Analysis with Python/venv/lib/python3.6/site-packages/fix_yahoo_finance/__init__.py", line 181, in download
    if not tickers[-chunks:].empty:
AttributeError: 'list' object has no attribute 'empty'`

**Comment by Sdoof** [comment]
Why closing this thread if it is not fixed?

**Comment by ranaroussi** [comment]
It is :) Please upgrade to the latest version and retry:

```bash
$ pip install fix_yahoo_finance -U
```
