### ISSUE TITLE
AttributeError: 'list' object has no attribute 'empty'

### ISSUE THREAD

**Issue by ep12** [ranaroussi/fix-yahoo-finance#46]
Running this code throws the above error.
```python
import pandas as pd
import pandas_datareader.data as pdr
import fix_yahoo_finance as yf
yf.pdr_override()
start = dt.datetime(2000, 1, 1)
end = dt.datetime.now()
df = yf.download(  # pdr.get_data_yahoo
	'SPY',
	start=start,
	end=end,
	as_panel=False,
	group_by='ticker',
	auto_adjust=False,
	progress=False,
	threads=16)
```
It seems to be related to multithreading. Running it without *threads=16* works...

Python 3\lib\site-packages\fix_yahoo_finance\__init__.py
in download(tickers, start, end, as_panel, group_by, auto_adjust, progress, actions, threads, **kwargs)
    179                             auto_adjust=auto_adjust, progress=progress,
    180                             actions=actions, **kwargs)
--> **181         if not tickers[-chunks:].empty:**
    182             download_thread(tickers[-chunks:], start=start, end=end,
    183                             auto_adjust=auto_adjust, progress=progress,

**Comment by soup-campbell** [comment]
Same Problem
    if(len(ListOfTickers)<100):
        THREADS=1
    else:
        THREADS=10
       df1=yf.download(ListOfTickers,start=START_DATE,as_panel=False,progress=False,threads=THREADS)

**Comment by soup-campbell** [comment]
processing  2018-08-01   1769  Tickers
Exception in process_one_day_v3(2018-08-01)
'list' object has no attribute 'empty'
processing  2018-07-31   10298  Tickers
Exception in process_one_day_v3(2018-07-31)
'list' object has no attribute 'empty'
processing  2018-07-28   71  Tickers
