### ISSUE TITLE
how to get data for today?

### ISSUE THREAD

**Issue by Sandy4321** [ranaroussi/fix-yahoo-finance#48]
today is Mar 28 , 2018
how to get data for today?

import fix_yahoo_finance as yf
import datetime as dt
import time
#data = yf.download("SPY", start="2017-01-01", end="2017-04-30")

data = yf.download("SPY", start="2018-03-24", end="2018-03-28")

it is what I get
data
                  Open        High         Low       Close   Adj Close  \
Date                                                                     
2018-03-26  262.130005  265.429993  259.410004  265.109985  265.109985   
2018-03-27  266.170013  266.769989  258.839996  260.600006  260.600006   

               Volume  
Date                   
2018-03-26  141956100  
2018-03-27  126354700 

but for today there is now data?

**Comment by jud2012** [comment]
Happens also to me.
Is it possible to get today closing price after trading hours, around 17:00 EST time?
