### ISSUE TITLE
list of tickers?

### ISSUE THREAD

**Issue by PeterXiaoGuo** [ranaroussi/fix-yahoo-finance#49]
Thanks this excellent packages for yahoo finance!!!!!!!!!

It saves my group project for visualization especially my group member is non-active before DDL.

Could anyone help to make me clear where can I find tickers??

i.e. Google company stock, Gold price, foreign exchange info. like U.S.D? 

Many thanks in advance!

Best,
Peter

**Comment by soup-campbell** [comment]
here is a start
https://www.nasdaq.com/screening/company-list.aspx

**Comment by pdhimal1** [comment]
https://github.com/pdhimal1/AI-Project/tree/master/Data
