### ISSUE TITLE
Panel is deprecated and will be removed in a future version.

### ISSUE THREAD

**Issue by rana9903** [ranaroussi/fix-yahoo-finance#51]
I am seeing following error. Could you please have a look  please. 

[*********************100%***********************]  1 of 1 downloaded
C:\stock\stockcharts\graph.py:57: FutureWarning: 
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.

  data = yf.download('XEG.TO', start=StartDate, end=endDate)
C:\Python27\lib\site-packages\fix_yahoo_finance\__init__.py:199: FutureWarning: 
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.

**Comment by ranaroussi** [comment]
Version 0.0.22 removed deprecated Panel support.

As for the flatting thing: use:

```python
import re
import fix_yahoo_finance

# get data
df = yf.download(['GOOG', 'AAPL']).dropna()

# flatten data
df = pd.DataFrame(df.to_records())

# rename columns
df.columns = [re.sub('[()\',]', '', e) for e in df.columns]

df.head()
```
