### ISSUE TITLE
downloads not working for me since week of 9/3/2018

### ISSUE THREAD

**Issue by DonaldPG** [ranaroussi/fix-yahoo-finance#57]
fix-yahoo-finance has worked perfectly until 9/4 or 9/5/18. Now I cannot get any quotes.
It seems to be related to the yahoo website. Is this happening for everyone, or just me? thanks

res = _requests.get('https://finance.yahoo.com/quote/SPY/history')
print res
<Response [404]>

**Comment by cantoluna1** [comment]
try to add option "auto_adjust = False"
