### ISSUE TITLE
download using actions="only" does not work for me since version 0.0.22

### ISSUE THREAD

**Issue by mercgreg** [ranaroussi/fix-yahoo-finance#58]
I use fix_yahoo_finance to download pure dividend information. Since the removal of the
deprecated Panel in version 0.0.22 this no longer seems to work. It works fine for downloading the regular price data. I think its related to specifically looking for certain columns in the scraped data. The error message is "KeyError: "['Open' 'High' 'Low' 'Close' 'Adj Close' 'Volume'] not in index". You can replicate the problem in version 0.0.21 by calling the download function with actions="only", and as_panel=False.

**Comment by just2610** [comment]
Having the same issue...
