### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by k7e7n7t** [ranaroussi/fix-yahoo-finance#7]
Thanks a bunch for this fix!
I tested a SP500 download but some tickers were rejected: CAT, DRI, GRMN
Companies are good. I ran your suggested native code as a test and same issue.  

```
The following tickers failed to download:
 DRI
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-7-43f2f0d22457> in <module>()
      1 import fix_yahoo_finance as yf
----> 2 data = yf.download("dri", start="2017-01-01", end="2017-4-30")
      3 print(data)

/home/kent/anaconda3/lib/python3.6/site-packages/fix_yahoo_finance/__init__.py in download(tickers, start, end, as_panel, group_by, auto_adjust, progress, *args, **kwargs)
    207     # return single df if only one ticker
    208     if len(tickers) == 1:
--> 209         data = dfs[tickers[0]]
    210 
    211     return data

KeyError: 'DRI'
```
Any suggestions? Thank you.

**Comment by jainraje** [comment]
FYI, I observed the same issue with both GRMN, CAT and others when running a looped download of many symbols (my tests are w/ 7000+ tickers). I tested the failed tickers manually using a juypter notebook running the function one ticker at a time. CAT and GRMN specifically seemed intermittent in that sometimes data was retrieved while others no data was retrieved. I reran the loop with only failed tickers and then they then downloaded. Seems there still may be some issues w/ the Yahoo end point.

**Comment by k7e7n7t** [comment]
You're right.  I test again this morning and now they work. Weird....thanks.

**Comment by ranaroussi** [comment]
I've added thread support in 0.0.9, so it should run faster than a loop.

Just add ``threads=INT`` to your code. I use ``threads=len(tickers)//10)`` myself...

Upgrade using:

```bash
$ pip install fix_yahoo_finance --upgrade --no-cache-dir
```

Can you please check if this is working better for you?
